services:
  stats-server:
    build: ewm-stats-service/stats-server
    image: stats-server-image
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stats
      - SPRING_DATASOURCE_USERNAME=postgresdb
      - SPRING_DATASOURCE_PASSWORD=123456

  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgresdb
      - POSTGRES_USER=postgresdb
      - POSTGRES_DB=ewm-stats
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  ewm-service:
    build: ewm-main-service
    image: ewm-main-service-image
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:6540/ewm-service
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=dbuser

  ewm-db:
    image: postgres:16.1
    container_name: ewm-db
    ports:
      - "6540:6540"
    environment:
      - POSTGRES_PASSWORD=dbuser
      - POSTGRES_USER=dbuser
      - POSTGRES_DB=ewm-service
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10